#include "EndingScene.h"

using namespace std;

void EndingScene1() // 방패
{
	int setmode;

	setmode = _setmode(_fileno(stdout), _O_U8TEXT);

	wcout << L"           ██████████           " << endl;
	wcout << L"     ██████          ██████	   " << endl;
	wcout << L"   ██                      ██   " << endl;
	Sleep(400);   
	wcout << L"   ██                      ██   " << endl;
	wcout << L"   ██                      ██   " << endl;
	wcout << L"   ██                      ██   " << endl;
	wcout << L"   ██                      ██   " << endl;
	wcout << L"   ██                      ██   " << endl;
	Sleep(400);   
	wcout << L"     ██                  ██	   " << endl;
	wcout << L"       ██              ██	   " << endl;
	wcout << L"         ██          ██		   " << endl;
	wcout << L"           ██      ██		   " << endl;
	wcout << L"             ██████			   " << endl;
	Sleep(400);

	setmode = _setmode(_fileno(stdout), _O_TEXT);

	cout << "방패 획득!" << endl;
	Sleep(2000);
	system("cls");
	
	ShieldAnimation();

	system("cls");
	cout << "1번째 엔딩 - 방패수집가" << endl;
}

void ShieldAnimation() {

	int setmode;

	setmode = _setmode(_fileno(stdout), _O_U8TEXT);

	wcout << L"           ██████████           " << endl;
	wcout << L"     ██████          ██████	   " << endl;
	wcout << L"   ██                      ██   " << endl;
	wcout << L"   ██                      ██   " << endl;
	wcout << L"   ██                      ██   " << endl;
	wcout << L"   ██                      ██   " << endl;
	wcout << L"   ██                      ██   " << endl;
	wcout << L"   ██                      ██   " << endl;
	wcout << L"     ██                  ██	   " << endl;
	wcout << L"       ██              ██	   " << endl;
	wcout << L"         ██          ██		   " << endl;
	wcout << L"           ██      ██		   " << endl;
	wcout << L"             ██████			   " << endl;
	Sleep(600);
	system("cls");
	wcout << L"           ██████████           " << endl;
	wcout << L"     ██████          ██████	   " << endl;
	wcout << L"   ██          ██          ██   " << endl;
	wcout << L"   ██          ██          ██   " << endl;
	wcout << L"   ██      ██████████      ██   " << endl;
	wcout << L"   ██          ██          ██   " << endl;
	wcout << L"   ██          ██          ██   " << endl;
	wcout << L"   ██          ██          ██   " << endl;
	wcout << L"     ██        ██        ██	   " << endl;
	wcout << L"       ██      ██      ██	   " << endl;
	wcout << L"         ██          ██		   " << endl;
	wcout << L"           ██      ██		   " << endl;
	wcout << L"             ██████			   " << endl;
	Sleep(600); 
	system("cls");
	wcout << L"             ██████              " << endl;
	wcout << L"           ████  ████		    " << endl;
	wcout << L"     ██████  ██  ██  ██████	    " << endl;
	wcout << L"   ████  ██  ██  ██  ██  ████    " << endl;
	wcout << L"   ██  ██  ████  ████  ██  ██    " << endl;
	wcout << L"   ██    ██  ██  ██  ██    ██    " << endl;
	wcout << L" ████████████  ██  ████████████  " << endl;
	wcout << L" ██          ██  ██          ██  " << endl;
	wcout << L" ████████████  ██  ████████████  " << endl;
	wcout << L"     ██      ██  ██      ██	    " << endl;
	wcout << L"       ██    ██  ██    ██	    " << endl;
	wcout << L"         ██  ██  ██  ██		    " << endl;
	wcout << L"           ████  ████		    " << endl;
	wcout << L"             ██  ██			    " << endl;
	wcout << L"             ██████			    " << endl;
	Sleep(600);
	system("cls");
	wcout << L"    ██████████████████████████    " << endl;
	wcout << L"    ██                      ██    " << endl;
	wcout << L"    ██                      ██    " << endl;
	wcout << L"    ██                      ██    " << endl;
	wcout << L"    ██                      ██    " << endl;
	wcout << L"    ██                      ██    " << endl;
	wcout << L"    ██                      ██    " << endl;
	wcout << L"    ██                      ██    " << endl;
	wcout << L"      ██                  ██      " << endl;
	wcout << L"        ██              ██        " << endl;
	wcout << L"          ██          ██          " << endl;
	wcout << L"            ██      ██            " << endl;
	wcout << L"              ██████              " << endl;
	Sleep(600);
	system("cls");
	wcout << L"    ██████████████████████████    " << endl;
	wcout << L"    ██        ██  ██        ██    " << endl;
	wcout << L"    ██        ██  ██        ██    " << endl;
	wcout << L"    ██    ██████████████    ██    " << endl;
	wcout << L"    ████████          ████████    " << endl;
	wcout << L"    ██    ██          ██    ██    " << endl;
	wcout << L"    ████████          ████████    " << endl;
	wcout << L"    ██      ██      ██      ██    " << endl;
	wcout << L"      ██      ██  ██      ██      " << endl;
	wcout << L"        ██    ██████    ██        " << endl;
	wcout << L"          ██  ██  ██  ██          " << endl;
	wcout << L"            ████  ████            " << endl;
	wcout << L"              ██████              " << endl;
	Sleep(600);
	system("cls");
	wcout << L"    ██████████████████████████    " << endl;
	wcout << L"    ██                      ██    " << endl;
	wcout << L"    ██    ██████████████    ██    " << endl;
	wcout << L"    ██  ██              ██  ██    " << endl;
	wcout << L"    ██  ██  ██  ██  ██  ██  ██    " << endl;
	wcout << L"    ██  ██  ██████████  ██  ██    " << endl;
	wcout << L"    ██  ██  ██  ██  ██  ██  ██    " << endl;
	wcout << L"    ██    ██    ██    ██    ██    " << endl;
	wcout << L"      ██    ██  ██  ██    ██      " << endl;
	wcout << L"        ██    ██  ██    ██        " << endl;
	wcout << L"          ██    ██    ██          " << endl;
	wcout << L"            ██      ██            " << endl;
	wcout << L"              ██████              " << endl;
	Sleep(600);
	system("cls");
	wcout << L"	            ██████████             " << endl;
	wcout << L"	        ████          ████         " << endl;
	wcout << L"	      ██                  ██       " << endl;
	wcout << L"	    ██                      ██     " << endl;
	wcout << L"	  ██                          ██   " << endl;
	wcout << L"	  ██                          ██   " << endl;
	wcout << L"	  ██                          ██   " << endl;
	wcout << L"	  ██                          ██   " << endl;
	wcout << L"	  ██                          ██   " << endl;
	wcout << L"	    ██                      ██     " << endl;
	wcout << L"	      ██                  ██       " << endl;
	wcout << L"	        ████          ████         " << endl;
	wcout << L"	            ██████████             " << endl;
	Sleep(600);
	system("cls");
	wcout << L"	            ██████████             " << endl;
	wcout << L"	        ████          ████         " << endl;
	wcout << L"	      ██                  ██       " << endl;
	wcout << L"	    ██        ██████        ██     " << endl;
	wcout << L"	  ██        ██      ██        ██   " << endl;
	wcout << L"	  ██      ██          ██      ██   " << endl;
	wcout << L"	  ██      ██   ████   ██      ██   " << endl;
	wcout << L"	  ██      ██          ██      ██   " << endl;
	wcout << L"	  ██        ██      ██        ██   " << endl;
	wcout << L"	    ██        ██████        ██     " << endl;
	wcout << L"	      ██                  ██       " << endl;
	wcout << L"	        ████          ████         " << endl;
	wcout << L"	            ██████████             " << endl;
	Sleep(600);
	system("cls");
	wcout << L"	            ██████████             " << endl;
	wcout << L"	        ████  ██  ██  ████         " << endl;
	wcout << L"	      ██      ██  ██      ██       " << endl;
	wcout << L"	    ██        ██████        ██     " << endl;
	wcout << L"	  ██        ██      ██        ██   " << endl;
	wcout << L"	  ██████████          ██████████   " << endl;
	wcout << L"	  ██      ██          ██      ██   " << endl;
	wcout << L"	  ██████████          ██████████   " << endl;
	wcout << L"	  ██        ██      ██        ██   " << endl;
	wcout << L"	    ██        ██████        ██     " << endl;
	wcout << L"	      ██      ██  ██      ██       " << endl;
	wcout << L"	        ████  ██  ██  ████         " << endl;
	wcout << L"	            ██████████             " << endl;
	Sleep(600);
	system("cls");

	setmode = _setmode(_fileno(stdout), _O_TEXT);
}

void EndingScene2() // 투척용 무기
{

}

void EndingScene3() // 단검
{

}

void EndingScene4() // 활
{

}

void EndingScene5()
{
	int setmode;

	setmode = _setmode(_fileno(stdout), _O_U8TEXT);

	//32

	wcout << L"	                                 " << endl;
	wcout << L"	            ██████████           " << endl;
	wcout << L"	          ████      ██           " << endl;
	Sleep(400);	          			            
	wcout << L"	          ██    ██               " << endl;
	wcout << L"	            ██    ████           " << endl;
	wcout << L"	            ████  ████           " << endl;
	Sleep(400);	          			            
	wcout << L"	                ██               " << endl;
	wcout << L"	                ████             " << endl;
	wcout << L"	                  ██             " << endl;
	Sleep(400);	                	            
	wcout << L"	                  ██             " << endl;
	wcout << L"	                  ██             " << endl;
	wcout << L"	                ██               " << endl;
	wcout << L"	                ██               " << endl;
	wcout << L"	                ██               " << endl;
	wcout << L"	                ██               " << endl;
	wcout << L"	                ██               " << endl;
	Sleep(400);

	setmode = _setmode(_fileno(stdout), _O_TEXT);

	cout << "마법지팡이 획득!" << endl;
	Sleep(2000);
	system("cls");

	StaffAnimation();

	system("cls");
	cout << "5번째 엔딩 - 미로파괴자" << endl;
}

void StaffAnimation() {
	int setmode;

	setmode = _setmode(_fileno(stdout), _O_U8TEXT);

	//32

	wcout << L"	                                 " << endl;
	wcout << L"	            ██████████           " << endl;
	wcout << L"	          ████      ██           " << endl;
	wcout << L"	          ██    ██               " << endl;
	wcout << L"	            ██    ████           " << endl;
	wcout << L"	            ████  ████           " << endl;
	wcout << L"	                ██               " << endl;
	wcout << L"	                ████             " << endl;
	wcout << L"	                  ██             " << endl;
	wcout << L"	                  ██             " << endl;
	wcout << L"	                  ██             " << endl;
	wcout << L"	                ██               " << endl;
	wcout << L"	                ██               " << endl;
	wcout << L"	                ██               " << endl;
	wcout << L"	                ██               " << endl;
	wcout << L"	                ██               " << endl;

	// 42
	system("cls");
	wcout << L"	                                     *     " << endl;
	wcout << L"	            ██████████     *               " << endl;
	wcout << L"	          ████      ██                     " << endl;
	wcout << L"	          ██    ██                         " << endl;
	wcout << L"	            ██    ████    *                " << endl;
	wcout << L"	            ████  ████             *       " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ████                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	Sleep(300);
	system("cls");
	wcout << L"	                                     *     " << endl;
	wcout << L"	            ██████████     *               " << endl;
	wcout << L"	          ████      ██                     " << endl;
	wcout << L"	          ██    ██             *           " << endl;
	wcout << L"	            ██    ████                     " << endl;
	wcout << L"	            ████  ████             *       " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ████                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	Sleep(300);
	system("cls");
	wcout << L"	                                     *     " << endl;
	wcout << L"	            ██████████     *               " << endl;
	wcout << L"	          ████      ██                     " << endl;
	wcout << L"	          ██    ██             **          " << endl;
	wcout << L"	            ██    ████                     " << endl;
	wcout << L"	            ████  ████                     " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ████        *              " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	Sleep(300);
	system("cls");
	wcout << L"	                                     *     " << endl;
	wcout << L"	            ██████████                     " << endl;
	wcout << L"	          ████      ██ *                   " << endl;
	wcout << L"	          ██    ██            ***          " << endl;
	wcout << L"	            ██    ████                     " << endl;
	wcout << L"	            ████  ████                     " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ████        *              " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	Sleep(300);
	system("cls");
	wcout << L"	                                           " << endl;
	wcout << L"	            ██████████                     " << endl;
	wcout << L"	          ████      ██ *        *          " << endl;
	wcout << L"	          ██    ██             ***         " << endl;
	wcout << L"	            ██    ████                  *  " << endl;
	wcout << L"	            ████  ████                     " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ████        *              " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	Sleep(300);
	system("cls");
	wcout << L"	                                           " << endl;
	wcout << L"	            ██████████                     " << endl;
	wcout << L"	          ████      ██ *        *          " << endl;
	wcout << L"	          ██    ██             ***         " << endl;
	wcout << L"	            ██    ████          *       *  " << endl;
	wcout << L"	            ████  ████                     " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ████                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	Sleep(300);
	system("cls");
	wcout << L"	                                           " << endl;
	wcout << L"	            ██████████                     " << endl;
	wcout << L"	          ████      ██          *          " << endl;
	wcout << L"	          ██    ██             ***         " << endl;
	wcout << L"	            ██    ████          *       *  " << endl;
	wcout << L"	            ████  ████                     " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ████                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	Sleep(300);
	system("cls");
	wcout << L"	                                           " << endl;
	wcout << L"	            ██████████                     " << endl;
	wcout << L"	          ████      ██          *          " << endl;
	wcout << L"	          ██    ██             ***         " << endl;
	wcout << L"	            ██    ████          *          " << endl;
	wcout << L"	            ████  ████                     " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ████                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	Sleep(300);
	system("cls");
	wcout << L"	                                           " << endl;
	wcout << L"	          ██████████                       " << endl;
	wcout << L"	        ████      ██              *        " << endl;
	wcout << L"	        ██    ██                 ***       " << endl;
	wcout << L"	          ██    ████              *        " << endl;
	wcout << L"	          ████  ████                       " << endl;
	wcout << L"	              ██                           " << endl;
	wcout << L"	              ████                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	              ██                           " << endl;
	wcout << L"	              ██                           " << endl;
	wcout << L"	              ██                           " << endl;
	wcout << L"	              ██                           " << endl;
	wcout << L"	              ██                           " << endl;
	Sleep(300);
	system("cls");
	wcout << L"	                                           " << endl;
	wcout << L"	      ██████████                           " << endl;
	wcout << L"	    ████      ██                   *       " << endl;
	wcout << L"	    ██    ██                      ***      " << endl;
	wcout << L"	      ██    ████                   *       " << endl;
	wcout << L"	      ████  ████                           " << endl;
	wcout << L"	          ██                               " << endl;
	wcout << L"	          ████                             " << endl;
	wcout << L"	            ██                             " << endl;
	wcout << L"	            ██                             " << endl;
	wcout << L"	            ██                             " << endl;
	wcout << L"	          ██                               " << endl;
	wcout << L"	          ██                               " << endl;
	wcout << L"	          ██                               " << endl;
	wcout << L"	          ██                               " << endl;
	wcout << L"	          ██                               " << endl;
	Sleep(300);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"  ██████████                                " << endl;
	wcout << L"████      ██                           *    " << endl;
	wcout << L"██    ██                              ***   " << endl;
	wcout << L"  ██    ████                           *    " << endl;
	wcout << L"  ████  ████                                " << endl;
	wcout << L"      ██                                    " << endl;
	wcout << L"      ████                                  " << endl;
	wcout << L"        ██                                  " << endl;
	wcout << L"        ██                                  " << endl;
	wcout << L"        ██                                  " << endl;
	wcout << L"      ██                                    " << endl;
	wcout << L"      ██                                    " << endl;
	wcout << L"      ██                                    " << endl;
	wcout << L"      ██                                    " << endl;
	wcout << L"      ██                                    " << endl;
	Sleep(300);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"███████                                     " << endl;
	wcout << L"     ██                                 *   " << endl;
	wcout << L" ██                                    ***  " << endl;
	wcout << L"   ████                                 *   " << endl;
	wcout << L"█  ████                                     " << endl;
	wcout << L" ██                                         " << endl;
	wcout << L" ████                                       " << endl;
	wcout << L"   ██                                       " << endl;
	wcout << L"   ██                                       " << endl;
	wcout << L"   ██                                       " << endl;
	wcout << L" ██                                         " << endl;
	wcout << L" ██                                         " << endl;
	wcout << L" ██                                         " << endl;
	wcout << L" ██                                         " << endl;
	wcout << L" ██                                         " << endl;
	Sleep(300);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"███                                         " << endl;
	wcout << L" ██                                       * " << endl;
	wcout << L"                                         ***" << endl;
	wcout << L"███                                       * " << endl;
	wcout << L"███                                         " << endl;
	wcout << L"                                            " << endl;
	wcout << L"█                                           " << endl;
	wcout << L"█                                           " << endl;
	wcout << L"█                                           " << endl;
	wcout << L"█                                           " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(300);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                           *" << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(300);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(1500);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"*                                           " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(200);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L" *                                          " << endl;
	wcout << L"***                                         " << endl;
	wcout << L" *                                          " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(200);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"   *                                        " << endl;
	wcout << L"  ***                                       " << endl;
	wcout << L"   *                                        " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(200);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"     *                                      " << endl;
	wcout << L"    ***                                     " << endl;
	wcout << L"     *                                      " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(200);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"      *                                     " << endl;
	wcout << L"     ***                                    " << endl;
	wcout << L"      *                                     " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(500);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"   --                                       " << endl;
	wcout << L"      *                                     " << endl;
	wcout << L"     ***                                    " << endl;
	wcout << L"  --  *                                     " << endl;
	wcout << L"     --                                     " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(50);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L" ----                                       " << endl;
	wcout << L"      *                                     " << endl;
	wcout << L"     ***                                    " << endl;
	wcout << L"----  *                                     " << endl;
	wcout << L"   ----                                     " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(50);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L" -       -                                  " << endl;
	wcout << L"   -  *                                     " << endl;
	wcout << L"     ***                                    " << endl;
	wcout << L"-     *                                     " << endl;
	wcout << L"   -    -                                   " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(50);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"       ---                                  " << endl;
	wcout << L" ---  *                                     " << endl;
	wcout << L"     ***                                    " << endl;
	wcout << L"      *                                     " << endl;
	wcout << L"      ---                                   " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(50);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"       -                                    " << endl;
	wcout << L" -    *                                     " << endl;
	wcout << L"     ***                                    " << endl;
	wcout << L"      *                                     " << endl;
	wcout << L"      -                                     " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(50);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"   --                                       " << endl;
	wcout << L"      *                                     " << endl;
	wcout << L"     ***                                    " << endl;
	wcout << L"  --  *                                     " << endl;
	wcout << L"     --                                     " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(50);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L" ----                                       " << endl;
	wcout << L"      *                                     " << endl;
	wcout << L"     ***                                    " << endl;
	wcout << L"----  *                                     " << endl;
	wcout << L"   ----                                     " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(50);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L" -       -                                  " << endl;
	wcout << L"   -  *                                     " << endl;
	wcout << L"     ***                                    " << endl;
	wcout << L"-     *                                     " << endl;
	wcout << L"   -    -                                   " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(50);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"       ---                                  " << endl;
	wcout << L" ---  *                                     " << endl;
	wcout << L"     ***                                    " << endl;
	wcout << L"      *                                     " << endl;
	wcout << L"      ---                                   " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(50);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"       -                                    " << endl;
	wcout << L" -    *                                     " << endl;
	wcout << L"     ***                                    " << endl;
	wcout << L"      *                                     " << endl;
	wcout << L"      -                                     " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(50);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"   --                                       " << endl;
	wcout << L"      *                                     " << endl;
	wcout << L"     ***                                    " << endl;
	wcout << L"  --  *                                     " << endl;
	wcout << L"     --                                     " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(50);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L" ----                                       " << endl;
	wcout << L"      *                                     " << endl;
	wcout << L"     ***                                    " << endl;
	wcout << L"----  *                                     " << endl;
	wcout << L"   ----                                     " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(50);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L" -       -                                  " << endl;
	wcout << L"   -  *                                     " << endl;
	wcout << L"     ***                                    " << endl;
	wcout << L"-     *                                     " << endl;
	wcout << L"   -    -                                   " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(50);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"       ---                                  " << endl;
	wcout << L" ---  *                                     " << endl;
	wcout << L"     ***                                    " << endl;
	wcout << L"      *                                     " << endl;
	wcout << L"      ---                                   " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(50);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"       -                                    " << endl;
	wcout << L" -    *                                     " << endl;
	wcout << L"     ***                                    " << endl;
	wcout << L"      *                                     " << endl;
	wcout << L"      -                                     " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(50);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                          ██" << endl;
	wcout << L"                                          ██" << endl;
	wcout << L"      *                                   ██" << endl;
	wcout << L"     ***                                  ██" << endl;
	wcout << L"      *                                   ██" << endl;
	wcout << L"                                          ╚═" << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(50);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                 ███╗   ███╗" << endl;
	wcout << L"                                 ████╗ ████║" << endl;
	wcout << L"       *                         ██╔████╔██║" << endl;
	wcout << L"      ***                        ██║╚██╔╝██║" << endl;
	wcout << L"       *                         ██║ ╚═╝ ██║" << endl;
	wcout << L"                                 ╚═╝     ╚═╝" << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(50);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                      ███╗   ███╗ █████╗ ███" << endl;
	wcout << L"                      ████╗ ████║██╔══██╗╚══" << endl;
	wcout << L"        *             ██╔████╔██║███████║  █" << endl;
	wcout << L"       ***            ██║╚██╔╝██║██╔══██║ ██" << endl;
	wcout << L"        *             ██║ ╚═╝ ██║██║  ██║███" << endl;
	wcout << L"                      ╚═╝     ╚═╝╚═╝  ╚═╝╚══" << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(80);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"         ███╗   ███╗ █████╗ ███████╗███████╗" << endl;
	wcout << L"         ████╗ ████║██╔══██╗╚══███╔╝██╔════╝" << endl;
	wcout << L"         ██╔██*█╔██║███████║  ███╔╝ █████╗" << endl;
	wcout << L"         ██║╚***╝██║██╔══██║ ███╔╝  ██╔══╝" << endl;
	wcout << L"         ██║ ╚*╝ ██║██║  ██║███████╗███████╗" << endl;
	wcout << L"         ╚═╝     ╚═╝╚═╝  ╚═╝╚══════╝╚══════╝" << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(100);
	system("cls");

	wcout << L"          _ ._  _ , _ ._			" << endl;
	wcout << L"        (_ ' ( `  )_  .__)		" << endl;
	wcout << L"      ( (  (    )   `)  ) _)		" << endl;
	wcout << L"     (__ (_   (_ . _) _) ,__)	" << endl;
	wcout << L"         `~~`\ ' . /`~~`			" << endl;
	wcout << L"              ;   ;				" << endl;
	wcout << L"              /   \				" << endl;
	wcout << L"_____________/_ __ \_____________" << endl;
	Sleep(1000);

	setmode = _setmode(_fileno(stdout), _O_TEXT);
}
