#include "EndingScene.h"

using namespace std;

void EndingScene1()
{

}

void EndingScene2()
{

}

void EndingScene3()
{

}

void EndingScene4()
{

}

void EndingScene5()
{
	int setmode;

	setmode = _setmode(_fileno(stdout), _O_U8TEXT);

	//32

	wcout << L"	                                 " << endl;
	wcout << L"	            ██████████           " << endl;
	wcout << L"	          ████      ██           " << endl;
	Sleep(400);	          			            
	wcout << L"	          ██    ██               " << endl;
	wcout << L"	            ██    ████           " << endl;
	wcout << L"	            ████  ████           " << endl;
	Sleep(400);	          			            
	wcout << L"	                ██               " << endl;
	wcout << L"	                ████             " << endl;
	wcout << L"	                  ██             " << endl;
	Sleep(400);	                	            
	wcout << L"	                  ██             " << endl;
	wcout << L"	                  ██             " << endl;
	wcout << L"	                ██               " << endl;
	wcout << L"	                ██               " << endl;
	wcout << L"	                ██               " << endl;
	wcout << L"	                ██               " << endl;
	wcout << L"	                ██               " << endl;
	Sleep(400);

	setmode = _setmode(_fileno(stdout), _O_TEXT);

	cout << "마법지팡이 획득!" << endl;
	Sleep(2000);
	system("cls");

	StaffAnimation();

	system("cls");
	cout << "5번째 엔딩 - 마법지팡이" << endl;
}

void StaffAnimation() {
	int setmode;

	setmode = _setmode(_fileno(stdout), _O_U8TEXT);

	//32

	wcout << L"	                                 " << endl;
	wcout << L"	            ██████████           " << endl;
	wcout << L"	          ████      ██           " << endl;
	wcout << L"	          ██    ██               " << endl;
	wcout << L"	            ██    ████           " << endl;
	wcout << L"	            ████  ████           " << endl;
	wcout << L"	                ██               " << endl;
	wcout << L"	                ████             " << endl;
	wcout << L"	                  ██             " << endl;
	wcout << L"	                  ██             " << endl;
	wcout << L"	                  ██             " << endl;
	wcout << L"	                ██               " << endl;
	wcout << L"	                ██               " << endl;
	wcout << L"	                ██               " << endl;
	wcout << L"	                ██               " << endl;
	wcout << L"	                ██               " << endl;

	// 42
	system("cls");
	wcout << L"	                                     *     " << endl;
	wcout << L"	            ██████████     *               " << endl;
	wcout << L"	          ████      ██                     " << endl;
	wcout << L"	          ██    ██                         " << endl;
	wcout << L"	            ██    ████    *                " << endl;
	wcout << L"	            ████  ████             *       " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ████                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	Sleep(300);
	system("cls");
	wcout << L"	                                     *     " << endl;
	wcout << L"	            ██████████     *               " << endl;
	wcout << L"	          ████      ██                     " << endl;
	wcout << L"	          ██    ██             *           " << endl;
	wcout << L"	            ██    ████                     " << endl;
	wcout << L"	            ████  ████             *       " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ████                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	Sleep(300);
	system("cls");
	wcout << L"	                                     *     " << endl;
	wcout << L"	            ██████████     *               " << endl;
	wcout << L"	          ████      ██                     " << endl;
	wcout << L"	          ██    ██             **          " << endl;
	wcout << L"	            ██    ████                     " << endl;
	wcout << L"	            ████  ████                     " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ████        *              " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	Sleep(300);
	system("cls");
	wcout << L"	                                     *     " << endl;
	wcout << L"	            ██████████                     " << endl;
	wcout << L"	          ████      ██ *                   " << endl;
	wcout << L"	          ██    ██            ***          " << endl;
	wcout << L"	            ██    ████                     " << endl;
	wcout << L"	            ████  ████                     " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ████        *              " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	Sleep(300);
	system("cls");
	wcout << L"	                                           " << endl;
	wcout << L"	            ██████████                     " << endl;
	wcout << L"	          ████      ██ *        *          " << endl;
	wcout << L"	          ██    ██             ***         " << endl;
	wcout << L"	            ██    ████                  *  " << endl;
	wcout << L"	            ████  ████                     " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ████        *              " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	Sleep(300);
	system("cls");
	wcout << L"	                                           " << endl;
	wcout << L"	            ██████████                     " << endl;
	wcout << L"	          ████      ██ *        *          " << endl;
	wcout << L"	          ██    ██             ***         " << endl;
	wcout << L"	            ██    ████          *       *  " << endl;
	wcout << L"	            ████  ████                     " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ████                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	Sleep(300);
	system("cls");
	wcout << L"	                                           " << endl;
	wcout << L"	            ██████████                     " << endl;
	wcout << L"	          ████      ██          *          " << endl;
	wcout << L"	          ██    ██             ***         " << endl;
	wcout << L"	            ██    ████          *       *  " << endl;
	wcout << L"	            ████  ████                     " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ████                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	Sleep(300);
	system("cls");
	wcout << L"	                                           " << endl;
	wcout << L"	            ██████████                     " << endl;
	wcout << L"	          ████      ██          *          " << endl;
	wcout << L"	          ██    ██             ***         " << endl;
	wcout << L"	            ██    ████          *          " << endl;
	wcout << L"	            ████  ████                     " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ████                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                  ██                       " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	Sleep(300);
	system("cls");
	wcout << L"	                                           " << endl;
	wcout << L"	          ██████████                       " << endl;
	wcout << L"	        ████      ██              *        " << endl;
	wcout << L"	        ██    ██                 ***       " << endl;
	wcout << L"	          ██    ████              *        " << endl;
	wcout << L"	          ████  ████                       " << endl;
	wcout << L"	              ██                           " << endl;
	wcout << L"	              ████                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	                ██                         " << endl;
	wcout << L"	              ██                           " << endl;
	wcout << L"	              ██                           " << endl;
	wcout << L"	              ██                           " << endl;
	wcout << L"	              ██                           " << endl;
	wcout << L"	              ██                           " << endl;
	Sleep(300);
	system("cls");
	wcout << L"	                                           " << endl;
	wcout << L"	      ██████████                           " << endl;
	wcout << L"	    ████      ██                   *       " << endl;
	wcout << L"	    ██    ██                      ***      " << endl;
	wcout << L"	      ██    ████                   *       " << endl;
	wcout << L"	      ████  ████                           " << endl;
	wcout << L"	          ██                               " << endl;
	wcout << L"	          ████                             " << endl;
	wcout << L"	            ██                             " << endl;
	wcout << L"	            ██                             " << endl;
	wcout << L"	            ██                             " << endl;
	wcout << L"	          ██                               " << endl;
	wcout << L"	          ██                               " << endl;
	wcout << L"	          ██                               " << endl;
	wcout << L"	          ██                               " << endl;
	wcout << L"	          ██                               " << endl;
	Sleep(300);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"  ██████████                                " << endl;
	wcout << L"████      ██                           *    " << endl;
	wcout << L"██    ██                              ***   " << endl;
	wcout << L"  ██    ████                           *    " << endl;
	wcout << L"  ████  ████                                " << endl;
	wcout << L"      ██                                    " << endl;
	wcout << L"      ████                                  " << endl;
	wcout << L"        ██                                  " << endl;
	wcout << L"        ██                                  " << endl;
	wcout << L"        ██                                  " << endl;
	wcout << L"      ██                                    " << endl;
	wcout << L"      ██                                    " << endl;
	wcout << L"      ██                                    " << endl;
	wcout << L"      ██                                    " << endl;
	wcout << L"      ██                                    " << endl;
	Sleep(300);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"███████                                     " << endl;
	wcout << L"     ██                                 *   " << endl;
	wcout << L" ██                                    ***  " << endl;
	wcout << L"   ████                                 *   " << endl;
	wcout << L"█  ████                                     " << endl;
	wcout << L" ██                                         " << endl;
	wcout << L" ████                                       " << endl;
	wcout << L"   ██                                       " << endl;
	wcout << L"   ██                                       " << endl;
	wcout << L"   ██                                       " << endl;
	wcout << L" ██                                         " << endl;
	wcout << L" ██                                         " << endl;
	wcout << L" ██                                         " << endl;
	wcout << L" ██                                         " << endl;
	wcout << L" ██                                         " << endl;
	Sleep(300);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"███                                         " << endl;
	wcout << L" ██                                       * " << endl;
	wcout << L"                                         ***" << endl;
	wcout << L"███                                       * " << endl;
	wcout << L"███                                         " << endl;
	wcout << L"                                            " << endl;
	wcout << L"█                                           " << endl;
	wcout << L"█                                           " << endl;
	wcout << L"█                                           " << endl;
	wcout << L"█                                           " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(300);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                           *" << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(300);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(1500);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"*                                           " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(200);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L" *                                          " << endl;
	wcout << L"***                                         " << endl;
	wcout << L" *                                          " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(200);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"   *                                        " << endl;
	wcout << L"  ***                                       " << endl;
	wcout << L"   *                                        " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(200);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"     *                                      " << endl;
	wcout << L"    ***                                     " << endl;
	wcout << L"     *                                      " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(200);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"      *                                     " << endl;
	wcout << L"     ***                                    " << endl;
	wcout << L"      *                                     " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(500);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"   --                                       " << endl;
	wcout << L"      *                                     " << endl;
	wcout << L"     ***                                    " << endl;
	wcout << L"  --  *                                     " << endl;
	wcout << L"     --                                     " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(50);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L" ----                                       " << endl;
	wcout << L"      *                                     " << endl;
	wcout << L"     ***                                    " << endl;
	wcout << L"----  *                                     " << endl;
	wcout << L"   ----                                     " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(50);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L" -       -                                  " << endl;
	wcout << L"   -  *                                     " << endl;
	wcout << L"     ***                                    " << endl;
	wcout << L"-     *                                     " << endl;
	wcout << L"   -    -                                   " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(50);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"       ---                                  " << endl;
	wcout << L" ---  *                                     " << endl;
	wcout << L"     ***                                    " << endl;
	wcout << L"      *                                     " << endl;
	wcout << L"      ---                                   " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(50);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"       -                                    " << endl;
	wcout << L" -    *                                     " << endl;
	wcout << L"     ***                                    " << endl;
	wcout << L"      *                                     " << endl;
	wcout << L"      -                                     " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(50);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"   --                                       " << endl;
	wcout << L"      *                                     " << endl;
	wcout << L"     ***                                    " << endl;
	wcout << L"  --  *                                     " << endl;
	wcout << L"     --                                     " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(50);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L" ----                                       " << endl;
	wcout << L"      *                                     " << endl;
	wcout << L"     ***                                    " << endl;
	wcout << L"----  *                                     " << endl;
	wcout << L"   ----                                     " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(50);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L" -       -                                  " << endl;
	wcout << L"   -  *                                     " << endl;
	wcout << L"     ***                                    " << endl;
	wcout << L"-     *                                     " << endl;
	wcout << L"   -    -                                   " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(50);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"       ---                                  " << endl;
	wcout << L" ---  *                                     " << endl;
	wcout << L"     ***                                    " << endl;
	wcout << L"      *                                     " << endl;
	wcout << L"      ---                                   " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(50);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"       -                                    " << endl;
	wcout << L" -    *                                     " << endl;
	wcout << L"     ***                                    " << endl;
	wcout << L"      *                                     " << endl;
	wcout << L"      -                                     " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(50);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"   --                                       " << endl;
	wcout << L"      *                                     " << endl;
	wcout << L"     ***                                    " << endl;
	wcout << L"  --  *                                     " << endl;
	wcout << L"     --                                     " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(50);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L" ----                                       " << endl;
	wcout << L"      *                                     " << endl;
	wcout << L"     ***                                    " << endl;
	wcout << L"----  *                                     " << endl;
	wcout << L"   ----                                     " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(50);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L" -       -                                  " << endl;
	wcout << L"   -  *                                     " << endl;
	wcout << L"     ***                                    " << endl;
	wcout << L"-     *                                     " << endl;
	wcout << L"   -    -                                   " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(50);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"       ---                                  " << endl;
	wcout << L" ---  *                                     " << endl;
	wcout << L"     ***                                    " << endl;
	wcout << L"      *                                     " << endl;
	wcout << L"      ---                                   " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(50);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"       -                                    " << endl;
	wcout << L" -    *                                     " << endl;
	wcout << L"     ***                                    " << endl;
	wcout << L"      *                                     " << endl;
	wcout << L"      -                                     " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(50);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                          ██" << endl;
	wcout << L"                                          ██" << endl;
	wcout << L"      *                                   ██" << endl;
	wcout << L"     ***                                  ██" << endl;
	wcout << L"      *                                   ██" << endl;
	wcout << L"                                          ╚═" << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(50);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                 ███╗   ███╗" << endl;
	wcout << L"                                 ████╗ ████║" << endl;
	wcout << L"       *                         ██╔████╔██║" << endl;
	wcout << L"      ***                        ██║╚██╔╝██║" << endl;
	wcout << L"       *                         ██║ ╚═╝ ██║" << endl;
	wcout << L"                                 ╚═╝     ╚═╝" << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(50);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                      ███╗   ███╗ █████╗ ███" << endl;
	wcout << L"                      ████╗ ████║██╔══██╗╚══" << endl;
	wcout << L"        *             ██╔████╔██║███████║  █" << endl;
	wcout << L"       ***            ██║╚██╔╝██║██╔══██║ ██" << endl;
	wcout << L"        *             ██║ ╚═╝ ██║██║  ██║███" << endl;
	wcout << L"                      ╚═╝     ╚═╝╚═╝  ╚═╝╚══" << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(80);
	system("cls");
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"         ███╗   ███╗ █████╗ ███████╗███████╗" << endl;
	wcout << L"         ████╗ ████║██╔══██╗╚══███╔╝██╔════╝" << endl;
	wcout << L"         ██╔██*█╔██║███████║  ███╔╝ █████╗" << endl;
	wcout << L"         ██║╚***╝██║██╔══██║ ███╔╝  ██╔══╝" << endl;
	wcout << L"         ██║ ╚*╝ ██║██║  ██║███████╗███████╗" << endl;
	wcout << L"         ╚═╝     ╚═╝╚═╝  ╚═╝╚══════╝╚══════╝" << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	wcout << L"                                            " << endl;
	Sleep(100);
	system("cls");

	wcout << L"          _ ._  _ , _ ._			" << endl;
	wcout << L"        (_ ' ( `  )_  .__)		" << endl;
	wcout << L"      ( (  (    )   `)  ) _)		" << endl;
	wcout << L"     (__ (_   (_ . _) _) ,__)	" << endl;
	wcout << L"         `~~`\ ' . /`~~`			" << endl;
	wcout << L"              ;   ;				" << endl;
	wcout << L"              /   \				" << endl;
	wcout << L"_____________/_ __ \_____________" << endl;
	Sleep(1000);

		//███╗   ███╗ █████╗ ███████╗███████╗
		//████╗ ████║██╔══██╗╚══███╔╝██╔════╝
		//██╔████╔██║███████║  ███╔╝ █████╗
		//██║╚██╔╝██║██╔══██║ ███╔╝  ██╔══╝
		//██║ ╚═╝ ██║██║  ██║███████╗███████╗
		//╚═╝     ╚═╝╚═╝  ╚═╝╚══════╝╚══════╝



	setmode = _setmode(_fileno(stdout), _O_TEXT);
}
